baseURL = "https://konstbel.github.io/landing/"
theme = "ananke"
defaultContentLanguage = "ru"

[languages]
  [languages.ru]
    title = "Конституция"
    description = "Приближаем новую Беларусь"
  [languages.be]
    title = "Канстытуцыя"
    description = "Набліжаем новую Беларусь"
    weight = 2

[params]
  featured_image = "https://scontent.fvno1-1.fna.fbcdn.net/v/t1.0-9/70400549_494952407984177_7647418295364091904_o.jpg?_nc_cat=107&_nc_oc=AQmFGyeOTno9WCVyRRyzitg4npHEpLBjs7j3idk70vZ2lpPFfaWpdRa3_55CBNmgBaE&_nc_ht=scontent.fvno1-1.fna&oh=7a29f28de6e03d3cd6c1cec17e13e696&oe=5ECC0680"
  facebook = "https://www.facebook.com/svezhyvecer/"
  twitter = "https://twitter.com/Svezhyvecer"
  instagram = "https://www.instagram.com/constitution_belarus/"
  telegram = "https://t.me/s/svezhyvecer"
