baseURL = "https://konstbel.netlify.com/"
theme = "alherd"
defaultContentLanguage = "ru"
disableKinds = ['taxonomy', 'taxonomyTerm']
#defaultContentLanguageInSubdir = true
summaryLength = 40

[markup.goldmark.renderer]
unsafe= true

[languages.be]
weight = 2
title = "Канстытуцыя"
description = "Набліжаем новую Беларусь"
contentDir = "content/be"

[languages.ru]
weight= 1
title = "Конституция"
description = "Приближаем новую Беларусь"
contentDir = "content/ru"

[params]
help_url = "https://www.talaka.org/projects/3341/overview"
featured_image = "img/bg.jpg"
facebook = "https://www.facebook.com/svezhyvecer/"
twitter = "https://twitter.com/Svezhyvecer"
instagram = "https://www.instagram.com/constitution_belarus/"
telegram = "https://t.me/s/svezhyvecer"
vk = "https://vk.com/svezhyvecer"
youtube = "https://www.youtube.com/channel/UCPrAHimL4WejRN7udYFN_Sg"
mainSections = ["posts"]

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

# main menu
[[menu.main]]
URL = "/"
identifier = "main"
weight = 1

[[menu.main]]
URL = "about"
identifier = "about"
weight = 2

[[menu.main]]
URL = "join"
identifier = "join"
weight = 3

# footer menu
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1

[[menu.footer]]
URL = "tools"
name = "tools"
weight = 2


[params.banner]
bgImage = ""
title = "Что такое Свежий Ветер"
image = "img/book.svg"

[[params.social]]
icon = "ti-facebook" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-twitter-alt" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "#"
[[params.social]]
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "#"
