backend:
  name: github
  repo:  konstbel/landing
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog_ru'
    label: 'Посты (ru)'
    folder: 'content/ru/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Дата', name: 'date', widget: 'datetime' }
      - { label: 'Автор', name: 'author', widget: 'string', required: false }
      - { label: 'Описание', name: 'description', widget: 'string', required: false }
      - { label: 'Главное изображение', name: 'featured_image', widget: 'image'}
      - { label: 'Текст', name: 'body', widget: 'markdown' }
  - name: 'main_ru'
    label: 'Главная (ru)'
    file: 'content/ru/_index.md'
    editor:
      preview: true
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
  - name: 'about_ru'
    label: 'О нас (ru)'
    file: 'content/ru/about/_index.md'
    editor:
      preview: true
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
  - name: 'blog_be'
    label: 'Запісы (be)'
    folder: 'content/be/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Назва', name: 'title', widget: 'string' }
      - { label: 'Дата', name: 'date', widget: 'datetime' }
      - { label: 'Аўтар', name: 'author', widget: 'string', required: false }
      - { label: 'Апісанне', name: 'description', widget: 'string', required: false }
      - { label: 'Галоўная выява', name: 'featured_image', widget: 'image'}
      - { label: 'Тэкст', name: 'body', widget: 'markdown' }
  - name: 'main_be'
    label: 'Галоўная (be)'
    file: 'content/be/_index.md'
    editor:
      preview: true
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
  - name: 'about_be'
    label: 'Пра нас (be)'
    file: 'content/be/about/_index.md'
    editor:
      preview: true
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
