version: '3'
services:
  db:
    image: "postgres:12.2-alpine"
    volumes:
      - ./infrastructure/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=konstbel
      - POSTGRES_USER=konstbel
      - POSTGRES_PASSWORD=konstbelpassword
  backend_web:
    build: ./backend/
    working_dir: /app
    command: sh -c "yarn watch:dev"
    environment:
      - DATABASE_URL=postgres://konstbel:konstbelpassword@db:5432/konstbel
      - SECRET=verysecurestring
    ports:
      - '3000:3000'
    volumes:
      - './backend/server:/app/server:cached'
    depends_on:
      - db
