version: '3'
services:
  db:
    image: "postgres:12.2-alpine"
    volumes:
      - ./infrastructure/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
  backend_web:
    build: ./backend/
    working_dir: /app
    command: sh -c "yarn watch:dev"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET=${SECRET}
    ports:
      - '3000:3000'
    volumes:
      - './backend/server:/app/server:cached'
    depends_on:
      - db
